import { Inter } from 'next/font/google'
import './globals.css'
import Link from "next/link"
import LoginBtn from "@/app/LoginBtn";
const inter = Inter({ subsets: ['latin'] })
import { getServerSession } from 'next-auth'
import {authOptions} from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "@/app/LogoutBtn";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
    let session = await getServerSession(authOptions)
    console.log(session)

  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar">
        <Link href="/"
              className="logo">Appleforum</Link>
        <Link href="/list">List</Link>
        {/*<LoginBtn/>*/}
          {
              session ? <span>{session.user.name}<LogoutBtn/></span> : <LoginBtn/>
          }

      </div>
      {children}
      </body>
    </html>
  )
}
